// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_system.Models;

namespace Payment_system.Migrations
{
    [DbContext(typeof(Payment_systemContext))]
    [Migration("20180911172657_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Payment_system.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Appointment_Id");

                    b.Property<decimal>("Cash_Amount");

                    b.Property<int>("CreditCard_Num");

                    b.Property<decimal>("Credit_Amount");

                    b.Property<decimal>("Total_Amount");

                    b.Property<DateTime>("date");

                    b.Property<int>("prescription_Id");

                    b.HasKey("PaymentId");

                    b.ToTable("Payment");
                });
#pragma warning restore 612, 618
        }
    }
}
